# Generated by Django 4.1.1 on 2022-09-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_event', '0002_remove_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='compagny_name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_contact_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
