# Generated by Django 4.1.1 on 2022-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_event', '0003_rename_compagny_name_client_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
