# Generated by Django 4.1.1 on 2022-09-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_event', '0005_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='epic_event.contract', unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'assigned'), (3, 'in progress'), (4, 'ready'), (5, 'finished')], default=1),
        ),
    ]
