# Generated by Django 4.1.1 on 2022-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_event', '0006_alter_event_attendees_alter_event_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
