# Generated by Django 4.1.1 on 2022-09-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_event', '0007_alter_event_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='epic_event.contract'),
        ),
    ]
