# Generated by Django 4.1.1 on 2022-10-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_event', '0008_alter_event_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='status',
            new_name='signed',
        ),
    ]
