# Generated by Django 4.1.1 on 2022-10-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_event', '0009_rename_status_contract_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(default='default_mobile', max_length=20),
            preserve_default=False,
        ),
    ]
